version: "2"
services:
  plone:
    image: plone:5
    ports:
    - "8080"
    volumes:
    - ../../:/plone/instance/src/eea.sentry
    environment:
      ADDONS: "eea.sentry[test]"
      DEVELOP: "src/eea.sentry"
